/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations/index'
import { Route as OrganizationsOrganizationIdIndexRouteImport } from './routes/organizations/$organizationId/index'
import { Route as OrganizationsOrganizationIdProjectsIndexRouteImport } from './routes/organizations/$organizationId/projects/index'
import { Route as OrganizationsOrganizationIdProjectsProjectIdIndexRouteImport } from './routes/organizations/$organizationId/projects/$projectId/index'
import { Route as OrganizationsOrganizationIdProjectsProjectIdListRouteImport } from './routes/organizations/$organizationId/projects/$projectId/list'
import { Route as OrganizationsOrganizationIdProjectsProjectIdBoardRouteImport } from './routes/organizations/$organizationId/projects/$projectId/board'
import { Route as OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRouteImport } from './routes/organizations/$organizationId/projects/$projectId/tasks/$taskId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdIndexRoute =
  OrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdProjectsIndexRoute =
  OrganizationsOrganizationIdProjectsIndexRouteImport.update({
    id: '/organizations/$organizationId/projects/',
    path: '/organizations/$organizationId/projects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdIndexRoute =
  OrganizationsOrganizationIdProjectsProjectIdIndexRouteImport.update({
    id: '/organizations/$organizationId/projects/$projectId/',
    path: '/organizations/$organizationId/projects/$projectId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdListRoute =
  OrganizationsOrganizationIdProjectsProjectIdListRouteImport.update({
    id: '/organizations/$organizationId/projects/$projectId/list',
    path: '/organizations/$organizationId/projects/$projectId/list',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdBoardRoute =
  OrganizationsOrganizationIdProjectsProjectIdBoardRouteImport.update({
    id: '/organizations/$organizationId/projects/$projectId/board',
    path: '/organizations/$organizationId/projects/$projectId/board',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute =
  OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/organizations/$organizationId/projects/$projectId/tasks/$taskId',
    path: '/organizations/$organizationId/projects/$projectId/tasks/$taskId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/projects': typeof OrganizationsOrganizationIdProjectsIndexRoute
  '/organizations/$organizationId/projects/$projectId/board': typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  '/organizations/$organizationId/projects/$projectId/list': typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  '/organizations/$organizationId/projects/$projectId': typeof OrganizationsOrganizationIdProjectsProjectIdIndexRoute
  '/organizations/$organizationId/projects/$projectId/tasks/$taskId': typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/projects': typeof OrganizationsOrganizationIdProjectsIndexRoute
  '/organizations/$organizationId/projects/$projectId/board': typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  '/organizations/$organizationId/projects/$projectId/list': typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  '/organizations/$organizationId/projects/$projectId': typeof OrganizationsOrganizationIdProjectsProjectIdIndexRoute
  '/organizations/$organizationId/projects/$projectId/tasks/$taskId': typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/organizations/$organizationId/': typeof OrganizationsOrganizationIdIndexRoute
  '/organizations/$organizationId/projects/': typeof OrganizationsOrganizationIdProjectsIndexRoute
  '/organizations/$organizationId/projects/$projectId/board': typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  '/organizations/$organizationId/projects/$projectId/list': typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  '/organizations/$organizationId/projects/$projectId/': typeof OrganizationsOrganizationIdProjectsProjectIdIndexRoute
  '/organizations/$organizationId/projects/$projectId/tasks/$taskId': typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/organizations'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/projects'
    | '/organizations/$organizationId/projects/$projectId/board'
    | '/organizations/$organizationId/projects/$projectId/list'
    | '/organizations/$organizationId/projects/$projectId'
    | '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/organizations'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/projects'
    | '/organizations/$organizationId/projects/$projectId/board'
    | '/organizations/$organizationId/projects/$projectId/list'
    | '/organizations/$organizationId/projects/$projectId'
    | '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/organizations/'
    | '/organizations/$organizationId/'
    | '/organizations/$organizationId/projects/'
    | '/organizations/$organizationId/projects/$projectId/board'
    | '/organizations/$organizationId/projects/$projectId/list'
    | '/organizations/$organizationId/projects/$projectId/'
    | '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
  OrganizationsOrganizationIdIndexRoute: typeof OrganizationsOrganizationIdIndexRoute
  OrganizationsOrganizationIdProjectsIndexRoute: typeof OrganizationsOrganizationIdProjectsIndexRoute
  OrganizationsOrganizationIdProjectsProjectIdBoardRoute: typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  OrganizationsOrganizationIdProjectsProjectIdListRoute: typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  OrganizationsOrganizationIdProjectsProjectIdIndexRoute: typeof OrganizationsOrganizationIdProjectsProjectIdIndexRoute
  OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute: typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/': {
      id: '/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/projects/': {
      id: '/organizations/$organizationId/projects/'
      path: '/organizations/$organizationId/projects'
      fullPath: '/organizations/$organizationId/projects'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/projects/$projectId/': {
      id: '/organizations/$organizationId/projects/$projectId/'
      path: '/organizations/$organizationId/projects/$projectId'
      fullPath: '/organizations/$organizationId/projects/$projectId'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/projects/$projectId/list': {
      id: '/organizations/$organizationId/projects/$projectId/list'
      path: '/organizations/$organizationId/projects/$projectId/list'
      fullPath: '/organizations/$organizationId/projects/$projectId/list'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/projects/$projectId/board': {
      id: '/organizations/$organizationId/projects/$projectId/board'
      path: '/organizations/$organizationId/projects/$projectId/board'
      fullPath: '/organizations/$organizationId/projects/$projectId/board'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId/projects/$projectId/tasks/$taskId': {
      id: '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
      path: '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
      fullPath: '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
  OrganizationsOrganizationIdIndexRoute: OrganizationsOrganizationIdIndexRoute,
  OrganizationsOrganizationIdProjectsIndexRoute:
    OrganizationsOrganizationIdProjectsIndexRoute,
  OrganizationsOrganizationIdProjectsProjectIdBoardRoute:
    OrganizationsOrganizationIdProjectsProjectIdBoardRoute,
  OrganizationsOrganizationIdProjectsProjectIdListRoute:
    OrganizationsOrganizationIdProjectsProjectIdListRoute,
  OrganizationsOrganizationIdProjectsProjectIdIndexRoute:
    OrganizationsOrganizationIdProjectsProjectIdIndexRoute,
  OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute:
    OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
