/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations/$organizationId'
import { Route as OrganizationsOrganizationIdProjectsRouteImport } from './routes/organizations/$organizationId/projects'
import { Route as OrganizationsOrganizationIdProjectsProjectIdRouteImport } from './routes/organizations/$organizationId/projects/$projectId'
import { Route as OrganizationsOrganizationIdProjectsProjectIdListRouteImport } from './routes/organizations/$organizationId/projects/$projectId/list'
import { Route as OrganizationsOrganizationIdProjectsProjectIdBoardRouteImport } from './routes/organizations/$organizationId/projects/$projectId/board'
import { Route as OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRouteImport } from './routes/organizations/$organizationId/projects/$projectId/tasks/$taskId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const OrganizationsOrganizationIdProjectsRoute =
  OrganizationsOrganizationIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => OrganizationsOrganizationIdRoute,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdRoute =
  OrganizationsOrganizationIdProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => OrganizationsOrganizationIdProjectsRoute,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdListRoute =
  OrganizationsOrganizationIdProjectsProjectIdListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => OrganizationsOrganizationIdProjectsProjectIdRoute,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdBoardRoute =
  OrganizationsOrganizationIdProjectsProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => OrganizationsOrganizationIdProjectsProjectIdRoute,
  } as any)
const OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute =
  OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => OrganizationsOrganizationIdProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/organizations/$organizationId/projects': typeof OrganizationsOrganizationIdProjectsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId': typeof OrganizationsOrganizationIdProjectsProjectIdRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/board': typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  '/organizations/$organizationId/projects/$projectId/list': typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  '/organizations/$organizationId/projects/$projectId/tasks/$taskId': typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/organizations/$organizationId/projects': typeof OrganizationsOrganizationIdProjectsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId': typeof OrganizationsOrganizationIdProjectsProjectIdRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/board': typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  '/organizations/$organizationId/projects/$projectId/list': typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  '/organizations/$organizationId/projects/$projectId/tasks/$taskId': typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/register': typeof RegisterRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRouteWithChildren
  '/organizations/$organizationId/projects': typeof OrganizationsOrganizationIdProjectsRouteWithChildren
  '/organizations/$organizationId/projects/$projectId': typeof OrganizationsOrganizationIdProjectsProjectIdRouteWithChildren
  '/organizations/$organizationId/projects/$projectId/board': typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  '/organizations/$organizationId/projects/$projectId/list': typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  '/organizations/$organizationId/projects/$projectId/tasks/$taskId': typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/organizations'
    | '/register'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/projects'
    | '/organizations/$organizationId/projects/$projectId'
    | '/organizations/$organizationId/projects/$projectId/board'
    | '/organizations/$organizationId/projects/$projectId/list'
    | '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/organizations'
    | '/register'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/projects'
    | '/organizations/$organizationId/projects/$projectId'
    | '/organizations/$organizationId/projects/$projectId/board'
    | '/organizations/$organizationId/projects/$projectId/list'
    | '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/organizations'
    | '/register'
    | '/organizations/$organizationId'
    | '/organizations/$organizationId/projects'
    | '/organizations/$organizationId/projects/$projectId'
    | '/organizations/$organizationId/projects/$projectId/board'
    | '/organizations/$organizationId/projects/$projectId/list'
    | '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/organizations/$organizationId/projects': {
      id: '/organizations/$organizationId/projects'
      path: '/projects'
      fullPath: '/organizations/$organizationId/projects'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsRouteImport
      parentRoute: typeof OrganizationsOrganizationIdRoute
    }
    '/organizations/$organizationId/projects/$projectId': {
      id: '/organizations/$organizationId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/organizations/$organizationId/projects/$projectId'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdRouteImport
      parentRoute: typeof OrganizationsOrganizationIdProjectsRoute
    }
    '/organizations/$organizationId/projects/$projectId/list': {
      id: '/organizations/$organizationId/projects/$projectId/list'
      path: '/list'
      fullPath: '/organizations/$organizationId/projects/$projectId/list'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdListRouteImport
      parentRoute: typeof OrganizationsOrganizationIdProjectsProjectIdRoute
    }
    '/organizations/$organizationId/projects/$projectId/board': {
      id: '/organizations/$organizationId/projects/$projectId/board'
      path: '/board'
      fullPath: '/organizations/$organizationId/projects/$projectId/board'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdBoardRouteImport
      parentRoute: typeof OrganizationsOrganizationIdProjectsProjectIdRoute
    }
    '/organizations/$organizationId/projects/$projectId/tasks/$taskId': {
      id: '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/organizations/$organizationId/projects/$projectId/tasks/$taskId'
      preLoaderRoute: typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRouteImport
      parentRoute: typeof OrganizationsOrganizationIdProjectsProjectIdRoute
    }
  }
}

interface OrganizationsOrganizationIdProjectsProjectIdRouteChildren {
  OrganizationsOrganizationIdProjectsProjectIdBoardRoute: typeof OrganizationsOrganizationIdProjectsProjectIdBoardRoute
  OrganizationsOrganizationIdProjectsProjectIdListRoute: typeof OrganizationsOrganizationIdProjectsProjectIdListRoute
  OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute: typeof OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute
}

const OrganizationsOrganizationIdProjectsProjectIdRouteChildren: OrganizationsOrganizationIdProjectsProjectIdRouteChildren =
  {
    OrganizationsOrganizationIdProjectsProjectIdBoardRoute:
      OrganizationsOrganizationIdProjectsProjectIdBoardRoute,
    OrganizationsOrganizationIdProjectsProjectIdListRoute:
      OrganizationsOrganizationIdProjectsProjectIdListRoute,
    OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute:
      OrganizationsOrganizationIdProjectsProjectIdTasksTaskIdRoute,
  }

const OrganizationsOrganizationIdProjectsProjectIdRouteWithChildren =
  OrganizationsOrganizationIdProjectsProjectIdRoute._addFileChildren(
    OrganizationsOrganizationIdProjectsProjectIdRouteChildren,
  )

interface OrganizationsOrganizationIdProjectsRouteChildren {
  OrganizationsOrganizationIdProjectsProjectIdRoute: typeof OrganizationsOrganizationIdProjectsProjectIdRouteWithChildren
}

const OrganizationsOrganizationIdProjectsRouteChildren: OrganizationsOrganizationIdProjectsRouteChildren =
  {
    OrganizationsOrganizationIdProjectsProjectIdRoute:
      OrganizationsOrganizationIdProjectsProjectIdRouteWithChildren,
  }

const OrganizationsOrganizationIdProjectsRouteWithChildren =
  OrganizationsOrganizationIdProjectsRoute._addFileChildren(
    OrganizationsOrganizationIdProjectsRouteChildren,
  )

interface OrganizationsOrganizationIdRouteChildren {
  OrganizationsOrganizationIdProjectsRoute: typeof OrganizationsOrganizationIdProjectsRouteWithChildren
}

const OrganizationsOrganizationIdRouteChildren: OrganizationsOrganizationIdRouteChildren =
  {
    OrganizationsOrganizationIdProjectsRoute:
      OrganizationsOrganizationIdProjectsRouteWithChildren,
  }

const OrganizationsOrganizationIdRouteWithChildren =
  OrganizationsOrganizationIdRoute._addFileChildren(
    OrganizationsOrganizationIdRouteChildren,
  )

interface OrganizationsRouteChildren {
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRouteWithChildren
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrganizationIdRoute:
    OrganizationsOrganizationIdRouteWithChildren,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
